language: perl
perl:
  - '5.14'
  - '5.12'
  - '5.10'

env:
  matrix:
  - COVERALLS=true  DB=mysql
  - COVERALLS=false DB=mysql
  - COVERALLS=false DB=sqlite
  global:
    secure: IbEJR4ZkrgxYUJyQ0JxBY2NtBnJMvxKaRvVQaYutxLRW2qry3eFMJHjp3fFjmNRTK8vEobRODK2pAuXyTcYh/iThOwgXq4oS9cVBNc5/Vr5OsQgMqu/GHqDRW2WvTI0niSKZA5dq0yaDEShatwmEvLfz8berwN8QJM6XbVmT0FGwJBq9QG45t5hRbJVXsTgVGZad3nUjGhMoDD7iOkfApou40Tw6z2bFpItbTpmM8SOadOT26dPNaVA6Cn4+HO9kTXdFBOuq9/VoVe1s2ObsnVLf4jJqYcdHUg9L+VTp4xzfXIsvrzvPbAQm5Xj5JjjWqr43yEv6fOYQYtKdYhes1g3+wPrGTmcCjRm3SSp39RWpk9Po4o67kKmu1mG+gRSJwY5Xzj86TkO726cGhxK8v3Nra0h9rRAp+oeWJHAFVCYmeo5scZnrnEllLNc42pxsDXvcFS2nBwVcF5di82rSIT4RdgBN7C6wMBAzanUGibwJYuieBtJ5i4/TWu5wOQyohWv02OThs2YMsFry2gFVJKExbzmJMSYXos9AqjdP8iua/PFVTqNB4XeHQSYK3xxttYxASS0ZNb358OfnZhwx2Yvg1HNE7U0ShKkshw/KpoH132TP7C4usVSoxA28jnM0PvljRLRfWuBI62bsJr68b7X3m83eTZTaBKoge6l/f1w=

sudo: false

addons:
  apt:
    packages:
    - unzip

before_install:
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone -b bioperl-release-1-6-1 --depth 1 https://github.com/bioperl/bioperl-live.git

install:
  - cpanm -v --installdeps --notest .
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n DBD::SQLite
  - cp travisci/MultiTestDB.conf.travisci.mysql  modules/t/MultiTestDB.conf.mysql
  - cp travisci/MultiTestDB.conf.travisci.SQLite modules/t/MultiTestDB.conf.SQLite
  - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'
script: "./travisci/harness.sh"

jobs:
  include:
  - stage: trigger_dependent_builds
    script: "./travisci/trigger-dependent-build.sh"

matrix:
  exclude:
  - perl: '5.10'
    env: COVERALLS=false DB=mysql
  - perl: '5.12'
    env: COVERALLS=false DB=sqlite
  - perl: '5.12'
    env: COVERALLS=true  DB=mysql
  - perl: '5.14'
    env: COVERALLS=false DB=sqlite
  - perl: '5.14'
    env: COVERALLS=true  DB=mysql

notifications:
  email:
    on_success: always
    on_failure: always
  slack:
    secure: gTcWzQsVHKPxRJ1u0U2l2+QVujmG1uFW44kAO3l46V5Im5uLTOLeM20ykk6ox4kaPHLs5ky7NGzcJmTDLaHBKjI4Sa34l4tJd0lhkv+hKj9TSv5pDDCdUX8v869Nm8LqJKh26HqvVcN7eHFRatLD/tfYvvkaP1rLLhwLLdr7czQ=
