dist: focal

language: perl

perl:
  - '5.26'
  - '5.32'

services:
  - mysql

env:
  matrix:
  - DB=mysql
  - DB=sqlite
  global:
    secure: EbGoRzfTTy/nlGPRYOEhKcYnIIrUHeM5etlqdAsMrfOkCCVJe7/QIWUG7hx1qdprIPdrKZ0jnmzBO3STz5m+TrsE/rAZjTM/MyEtwxAFEsdNlOKeozyE4Y4kwFMOqiLAFhHPtd3JhV92VMj3VSGVLkhNaaXbz1kj/aU14hOhbT4=

before_install:
  - git clone --branch main --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git

install:
  # Install IO::Scalar before processing the cpanfile because one of the dependencies
  # of Test::FTP::Server requires it yet does not declare it as a dependency, and
  # cpanm - or to be precise the module CPAN::Meta::Prereqs - scrambles the order
  # of entries in cpanfiles (see https://github.com/miyagawa/cpanfile/issues/42).
  # Cpanfile upstream categorically refuses to implement the forcing of dependencies
  # (see https://github.com/miyagawa/cpanfile/issues/3) so we will have to keep this
  # here until either Net::FTPServer has been fixed or we stop using Test::FTP::Server
  - cpanm -v --notest --sudo Net::FTPServer Test::FTP::Server
  - cpanm -v --sudo --installdeps --notest .
  - cp travisci/MultiTestDB.conf.travisci.mysql  modules/t/MultiTestDB.conf.mysql
  - cp travisci/MultiTestDB.conf.travisci.SQLite modules/t/MultiTestDB.conf.SQLite
  - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'
  - mysql -u root -h localhost -e 'SET GLOBAL local_infile=1'

script: "./travisci/harness.sh"

matrix:
  exclude:
  - perl: '5.26'
    env: DB=sqlite

notifications:
  email:
    on_failure: change
  slack:
    rooms:
      secure: JSqXP1CEa5/0x1qn6WoJ4KgLIrSVk8rTBoyy75RBGBZekrJvX5SuSqbZGK4V+oq1pBsk60MOlOkRuMDYrLBcB2TcDRKBqvaWqEbKiJtbmOJTZjFFssPr1HdJ8C77OxBg7CS+IdMh6Hf7AyAkCwO+e0c6ihgvmgx9+MIwmdgGAfw=
    on_failure: change
