language: perl

perl:
  - '5.14'
  - '5.12'
  - '5.10'

env:
  matrix:
  - COVERALLS=true  DB=mysql
  - COVERALLS=false DB=mysql
  - COVERALLS=false DB=sqlite
  global:
    secure: EbGoRzfTTy/nlGPRYOEhKcYnIIrUHeM5etlqdAsMrfOkCCVJe7/QIWUG7hx1qdprIPdrKZ0jnmzBO3STz5m+TrsE/rAZjTM/MyEtwxAFEsdNlOKeozyE4Y4kwFMOqiLAFhHPtd3JhV92VMj3VSGVLkhNaaXbz1kj/aU14hOhbT4=

sudo: false

addons:
  apt:
    packages:
    - unzip

before_install:
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone -b bioperl-release-1-6-1 --depth 1 https://github.com/bioperl/bioperl-live.git

install:
  - cpanm -v --installdeps --notest .
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n DBD::SQLite
  - cp travisci/MultiTestDB.conf.travisci.mysql  modules/t/MultiTestDB.conf.mysql
  - cp travisci/MultiTestDB.conf.travisci.SQLite modules/t/MultiTestDB.conf.SQLite
  - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'

script: "./travisci/harness.sh"

jobs:
  include:
  - stage: trigger_dependent_builds
    script: "./travisci/trigger-dependent-build.sh"

matrix:
  exclude:
  - perl: '5.10'
    env: COVERALLS=false DB=mysql
  - perl: '5.12'
    env: COVERALLS=false DB=sqlite
  - perl: '5.12'
    env: COVERALLS=true  DB=mysql
  - perl: '5.14'
    env: COVERALLS=false DB=sqlite
  - perl: '5.14'
    env: COVERALLS=true  DB=mysql

notifications:
  email:
    on_failure: change
  slack:
    secure: mS8ac72wmNRN6sz9nNyoFf59xnC75sU7TW4v/kUfC6hTW8pmwdx4ss1P4qkegJJb3bvxj+oKQRUqk8BtApozPyNXTkBDTMjsPXH0IQ4uz9JE5PHIzLpW1PMPiiV/JbyM2LX8vUFm/CA1t/tiwzSQ3PqrN3KjTrqbcyrEe+hD+jQ=
    on_failure: change
